FROM node:20.19

# Create an application directory.
WORKDIR /usr/src/app

# Bundle application sources.
COPY ./src/ /usr/src/app

# Install application dependencies.
#RUN npm install

# start react.js.
# ※ docker環境の場合、--hostのオプションが必要となる
#CMD ["npm", "run", "dev", "--", "--host"]
